### ISSUE TITLE
create new firmware

### ISSUE THREAD

**Issue by ojris** [oxxxide/NAADLD4FIRMWARE#16]
could you post a how-to create a (new) firmware for the LD4?
-using the files in this repository
-using updated files
i see some new files since a few days with a few small changes (e.g. MIDI notes range updated)
so how can these changed files be executed/transformed into new firmware?
greets from belgium
j

**Comment by oxxxide** [comment]
Use SWD Interface and Progrrammer/Debugger. 
LD4 has "SWDIO" and "SWCLK"  pins on back the PCB.

**Comment by oxxxide** [comment]
If you are using TrueSTUDIO, the software is able to write your binary data via SWD.

**Comment by ojris** [comment]
ok great

can i do this in a windows environment or do i need LINUX?
(will programs compiled in SWD on Windows run on the ARM LD4 processor?)

jo

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by oxxxide** [comment]
I use it in a  windows version. 
But this place is not a TrueSTUDIO support center. read the documents about TrueSTUDIO.

**Comment by ojris** [comment]
hello,

can you create a new firmware for the LD4 with the changes you made the past month?

i can then test the upload procedure

greets,

joris
